//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_ADO_NET_DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplanes
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public double Price { get; set; }
        public int Speed { get; set; }
        public Nullable<int> VendorId { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
    }
}
