//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_ADO_NET_DatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities_ManufacturerAirplane : DbContext
    {
        public Entities_ManufacturerAirplane()
            : base("name=Entities_ManufacturerAirplane")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airplanes> Airplanes { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
    
        [DbFunction("Entities_ManufacturerAirplane", "GetAirplaineWithSpeedLess")]
        public virtual IQueryable<GetAirplaineWithSpeedLess_Result> GetAirplaineWithSpeedLess(Nullable<int> st)
        {
            var stParameter = st.HasValue ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAirplaineWithSpeedLess_Result>("[Entities_ManufacturerAirplane].[GetAirplaineWithSpeedLess](@st)", stParameter);
        }
    
        [DbFunction("Entities_ManufacturerAirplane", "GetManufacturerNameWithLengthLess")]
        public virtual IQueryable<string> GetManufacturerNameWithLengthLess(Nullable<int> st)
        {
            var stParameter = st.HasValue ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[Entities_ManufacturerAirplane].[GetManufacturerNameWithLengthLess](@st)", stParameter);
        }
    
        [DbFunction("Entities_ManufacturerAirplane", "GetManufacturerWithAirplaneMore")]
        public virtual IQueryable<string> GetManufacturerWithAirplaneMore(Nullable<int> st)
        {
            var stParameter = st.HasValue ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[Entities_ManufacturerAirplane].[GetManufacturerWithAirplaneMore](@st)", stParameter);
        }
    }
}
