//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_ADO_NET_DatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities_ProjectsEmployees : DbContext
    {
        public Entities_ProjectsEmployees()
            : base("name=Entities_ProjectsEmployees")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
    
        [DbFunction("Entities_ProjectsEmployees", "GetEmployeerWithAgeLess")]
        public virtual IQueryable<GetEmployeerWithAgeLess_Result> GetEmployeerWithAgeLess(Nullable<int> st)
        {
            var stParameter = st.HasValue ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetEmployeerWithAgeLess_Result>("[Entities_ProjectsEmployees].[GetEmployeerWithAgeLess](@st)", stParameter);
        }
    
        [DbFunction("Entities_ProjectsEmployees", "GetEmployeerWithLastNameLengthMoreOrEqual")]
        public virtual IQueryable<GetEmployeerWithLastNameLengthMoreOrEqual_Result> GetEmployeerWithLastNameLengthMoreOrEqual(Nullable<int> st)
        {
            var stParameter = st.HasValue ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetEmployeerWithLastNameLengthMoreOrEqual_Result>("[Entities_ProjectsEmployees].[GetEmployeerWithLastNameLengthMoreOrEqual](@st)", stParameter);
        }
    
        [DbFunction("Entities_ProjectsEmployees", "GetProjectWithMaxEmployees")]
        public virtual IQueryable<GetProjectWithMaxEmployees_Result> GetProjectWithMaxEmployees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetProjectWithMaxEmployees_Result>("[Entities_ProjectsEmployees].[GetProjectWithMaxEmployees]()");
        }
    }
}
