#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_ADO_NET_LinqToSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WpfApp_ADO_NET_CodeFirst.Model_ManufacturerAirplane")]
	public partial class DataClasses_ManufacturerAirplaneDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertAirplanes(Airplanes instance);
    partial void UpdateAirplanes(Airplanes instance);
    partial void DeleteAirplanes(Airplanes instance);
    partial void InsertManufacturers(Manufacturers instance);
    partial void UpdateManufacturers(Manufacturers instance);
    partial void DeleteManufacturers(Manufacturers instance);
    #endregion
		
		public DataClasses_ManufacturerAirplaneDataContext() : 
				base(global::WpfApp_ADO_NET_LinqToSQL.Properties.Settings.Default.WpfApp_ADO_NET_CodeFirst_Model_ManufacturerAirplaneConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_ManufacturerAirplaneDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_ManufacturerAirplaneDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_ManufacturerAirplaneDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_ManufacturerAirplaneDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Airplanes> Airplanes
		{
			get
			{
				return this.GetTable<Airplanes>();
			}
		}
		
		public System.Data.Linq.Table<Manufacturers> Manufacturers
		{
			get
			{
				return this.GetTable<Manufacturers>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAirplaineWithSpeedLess", IsComposable=true)]
		public IQueryable<GetAirplaineWithSpeedLessResult> GetAirplaineWithSpeedLess([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> st)
		{
			return this.CreateMethodCallQuery<GetAirplaineWithSpeedLessResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), st);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetManufacturerWithAirplaneMore", IsComposable=true)]
		public IQueryable<GetManufacturerWithAirplaneMoreResult> GetManufacturerWithAirplaneMore([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> st)
		{
			return this.CreateMethodCallQuery<GetManufacturerWithAirplaneMoreResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), st);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetManufacturerNameWithLengthLess", IsComposable=true)]
		public IQueryable<GetManufacturerNameWithLengthLessResult> GetManufacturerNameWithLengthLess([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> st)
		{
			return this.CreateMethodCallQuery<GetManufacturerNameWithLengthLessResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), st);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Airplanes")]
	public partial class Airplanes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Model;
		
		private double _Price;
		
		private int _Speed;
		
		private System.Nullable<int> _VendorId;
		
		private EntityRef<Manufacturers> _Manufacturers;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    partial void OnPriceChanging(double value);
    partial void OnPriceChanged();
    partial void OnSpeedChanging(int value);
    partial void OnSpeedChanged();
    partial void OnVendorIdChanging(System.Nullable<int> value);
    partial void OnVendorIdChanged();
    #endregion
		
		public Airplanes()
		{
			this._Manufacturers = default(EntityRef<Manufacturers>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float NOT NULL")]
		public double Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Speed", DbType="Int NOT NULL")]
		public int Speed
		{
			get
			{
				return this._Speed;
			}
			set
			{
				if ((this._Speed != value))
				{
					this.OnSpeedChanging(value);
					this.SendPropertyChanging();
					this._Speed = value;
					this.SendPropertyChanged("Speed");
					this.OnSpeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorId", DbType="Int")]
		public System.Nullable<int> VendorId
		{
			get
			{
				return this._VendorId;
			}
			set
			{
				if ((this._VendorId != value))
				{
					if (this._Manufacturers.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVendorIdChanging(value);
					this.SendPropertyChanging();
					this._VendorId = value;
					this.SendPropertyChanged("VendorId");
					this.OnVendorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Manufacturers_Airplanes", Storage="_Manufacturers", ThisKey="VendorId", OtherKey="VendorId", IsForeignKey=true)]
		public Manufacturers Manufacturers
		{
			get
			{
				return this._Manufacturers.Entity;
			}
			set
			{
				Manufacturers previousValue = this._Manufacturers.Entity;
				if (((previousValue != value) 
							|| (this._Manufacturers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Manufacturers.Entity = null;
						previousValue.Airplanes.Remove(this);
					}
					this._Manufacturers.Entity = value;
					if ((value != null))
					{
						value.Airplanes.Add(this);
						this._VendorId = value.VendorId;
					}
					else
					{
						this._VendorId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Manufacturers");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Manufacturers")]
	public partial class Manufacturers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VendorId;
		
		private string _BrandTitle;
		
		private string _Address;
		
		private string _Phone;
		
		private EntitySet<Airplanes> _Airplanes;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVendorIdChanging(int value);
    partial void OnVendorIdChanged();
    partial void OnBrandTitleChanging(string value);
    partial void OnBrandTitleChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    #endregion
		
		public Manufacturers()
		{
			this._Airplanes = new EntitySet<Airplanes>(new Action<Airplanes>(this.attach_Airplanes), new Action<Airplanes>(this.detach_Airplanes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VendorId
		{
			get
			{
				return this._VendorId;
			}
			set
			{
				if ((this._VendorId != value))
				{
					this.OnVendorIdChanging(value);
					this.SendPropertyChanging();
					this._VendorId = value;
					this.SendPropertyChanged("VendorId");
					this.OnVendorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandTitle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BrandTitle
		{
			get
			{
				return this._BrandTitle;
			}
			set
			{
				if ((this._BrandTitle != value))
				{
					this.OnBrandTitleChanging(value);
					this.SendPropertyChanging();
					this._BrandTitle = value;
					this.SendPropertyChanged("BrandTitle");
					this.OnBrandTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(MAX)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Manufacturers_Airplanes", Storage="_Airplanes", ThisKey="VendorId", OtherKey="VendorId")]
		public EntitySet<Airplanes> Airplanes
		{
			get
			{
				return this._Airplanes;
			}
			set
			{
				this._Airplanes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Airplanes(Airplanes entity)
		{
			this.SendPropertyChanging();
			entity.Manufacturers = this;
		}
		
		private void detach_Airplanes(Airplanes entity)
		{
			this.SendPropertyChanging();
			entity.Manufacturers = null;
		}
	}
	
	public partial class GetAirplaineWithSpeedLessResult
	{
		
		private int _Id;
		
		private string _Model;
		
		private double _Price;
		
		private int _Speed;
		
		private string _BrandTitle;
		
		public GetAirplaineWithSpeedLessResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float NOT NULL")]
		public double Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Speed", DbType="Int NOT NULL")]
		public int Speed
		{
			get
			{
				return this._Speed;
			}
			set
			{
				if ((this._Speed != value))
				{
					this._Speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandTitle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BrandTitle
		{
			get
			{
				return this._BrandTitle;
			}
			set
			{
				if ((this._BrandTitle != value))
				{
					this._BrandTitle = value;
				}
			}
		}
	}
	
	public partial class GetManufacturerWithAirplaneMoreResult
	{
		
		private string _BrandTitle;
		
		public GetManufacturerWithAirplaneMoreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandTitle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BrandTitle
		{
			get
			{
				return this._BrandTitle;
			}
			set
			{
				if ((this._BrandTitle != value))
				{
					this._BrandTitle = value;
				}
			}
		}
	}
	
	public partial class GetManufacturerNameWithLengthLessResult
	{
		
		private string _BrandTitle;
		
		public GetManufacturerNameWithLengthLessResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandTitle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BrandTitle
		{
			get
			{
				return this._BrandTitle;
			}
			set
			{
				if ((this._BrandTitle != value))
				{
					this._BrandTitle = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
