// <auto-generated />
namespace WpfApp_ADO_NET_CodeFirst.Migrations.ProjectsEmployees
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedEmployees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedEmployees));
        
        string IMigrationMetadata.Id
        {
            get { return "202010120821543_SeedEmployees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
